### PR TITLE
Fixed GUI with webcam functionality

### PR DESCRIPTION
**Pull request by vanboven073**

### CODE REVIEW

**Comment by vanboven073** [comment]
I did manage to fix the webcam functionality inside the GUI. Hopefully this helps you with the continuation of your project!

**Comment by manhcuong02** [comment]
@vanboven073 Thank you for your interest in my repository and for updating it. I will review your pull request in the next few days. Thank you.

**Comment by manhcuong02** [comment]
@vanboven073 Thank you for your pull request. I’ve reviewed it and it works great. Thank you for your contribution.

**Comment by vanboven073** [comment]
Hi!

Nice to see that you incorporated the fix! Are there any other specific things you want to add/fix?

I am happy to help!

Kind regards,

Bram van Boven

________________________________
Van: Nguyễn Mạnh Cường ***@***.***>
Verzonden: zaterdag 7 december 2024 14:36
Aan: manhcuong02/Pytorch-Age-Estimation ***@***.***>
CC: Bram | BeerMate ***@***.***>; Mention ***@***.***>
Onderwerp: Re: [manhcuong02/Pytorch-Age-Estimation] Fixed GUI with webcam functionality (PR #2)


Merged #2<https://github.com/manhcuong02/Pytorch-Age-Estimation/pull/2> into main.

**Comment by manhcuong02** [comment]
@vanboven073  Thank you for your interest in contributing. While I appreciate your offer, I'm currently focusing on developing the core functionalities of this repository. As I'm not particularly skilled in creating GUIs and haven't delved deep into it yet, I'm primarily working on the backend and building simple Streamlit demos to showcase the core features. In the future, I plan to refactor the core to support more advanced models like ArcFace or Inception ResNet v1. Thank you again for your support.

**Comment by vanboven073** [comment]
Hi,

My background is a master in AI! So my core skills are also not creating GUIs. If you need some help in implementing other models, let me know! I am always willing to assist.

Kind regards,

Bram van Boven


________________________________
Van: Nguyễn Mạnh Cường ***@***.***>
Verzonden: maandag 9 december 2024 10:01
Aan: manhcuong02/Pytorch-Age-Estimation ***@***.***>
CC: Bram | BeerMate ***@***.***>; Mention ***@***.***>
Onderwerp: Re: [manhcuong02/Pytorch-Age-Estimation] Fixed GUI with webcam functionality (PR #2)


@vanboven073<https://github.com/vanboven073> Thank you for your interest in contributing. While I appreciate your offer, I'm currently focusing on developing the core functionalities of this repository. As I'm not particularly skilled in creating GUIs and haven't delved deep into it yet, I'm primarily working on the backend and building simple Streamlit demos to showcase the core features. In the future, I plan to refactor the core to support more advanced models like ArcFace or Inception ResNet v1. Thank you again for your support.

**Pull request merged**
